spring.application.name=salesmanagementapi

################# MySQL #################
spring.datasource.url=jdbc:mysql://localhost:3306/salesmanagement
spring.datasource.username=root
spring.datasource.password=Root123456
spring.jpa.hibernate.ddl-auto=create-drop
################# MySQL #################
